<template>
	<div class="operations-page">
		<header class="hero"><div><p class="eyebrow">AOO CONTROL PLANE</p><h1>业务运营中心</h1><p>所有变更均需原因、请求幂等号和权限校验；高风险操作要求异人审批。</p></div><el-tag type="success" size="large">只走权威接口</el-tag></header>
		<el-tabs v-model="active" class="workspace">
			<el-alert v-if="loadError" data-state="error" :title="loadError" type="error" show-icon :closable="false" class="state-alert"><el-button link type="primary" @click="loadAll">重试</el-button></el-alert>
			<el-tab-pane label="玩法发布" name="profiles" v-if="can(B.profileList)">
				<el-table :data="profiles" v-loading="loading" empty-text="暂无已发布玩法" border><el-table-column v-for="column in profileColumns" :key="column" :prop="column" :label="column" show-overflow-tooltip /><el-table-column label="发布工作流" width="210"><template #default="{ row }"><el-button v-if="can(B.releaseRead)" text type="primary" @click="openRelease(row)">查看 / 操作</el-button></template></el-table-column></el-table>
			</el-tab-pane>
			<el-tab-pane label="运营开关" name="switches" v-if="can(B.switchList)"><el-table :data="switches" border><el-table-column v-for="column in columns(switches)" :key="column" :prop="column" :label="column" show-overflow-tooltip/><el-table-column label="操作"><template #default="{row}"><el-button v-if="can(B.switchUpdate)" type="warning" text @click="openResource('switch', row)">变更</el-button></template></el-table-column></el-table></el-tab-pane>
			<el-tab-pane label="客服申诉" name="appeals" v-if="can(B.appealList)"><el-table :data="appeals" border><el-table-column v-for="column in columns(appeals)" :key="column" :prop="column" :label="column" show-overflow-tooltip/><el-table-column label="操作"><template #default="{row}"><el-button v-if="can(B.appealResolve)" type="warning" text @click="openResource('appeal', row)">处理</el-button></template></el-table-column></el-table></el-tab-pane>
			<el-tab-pane label="账务对账" name="billing" v-if="can(B.reconciliation)"><div class="toolbar"><el-date-picker v-model="businessDate" value-format="YYYY-MM-DD"/><el-button type="primary" @click="loadReconciliation">重新对账</el-button><el-tag :type="balanced ? 'success' : 'danger'">{{ balanced ? '账务平衡' : '存在差异' }}</el-tag></div><el-table :data="differences" border><el-table-column v-for="column in columns(differences)" :key="column" :prop="column" :label="column" show-overflow-tooltip/></el-table></el-tab-pane>
			<el-tab-pane label="回放调查" name="investigation" v-if="can(B.investigationRead)"><el-form inline><el-form-item label="房间 ID"><el-input v-model="investigation.roomId"/></el-form-item><el-form-item label="局号"><el-input-number v-model="investigation.set" :min="0"/></el-form-item><el-form-item label="原因"><el-input v-model="investigation.reason" maxlength="200"/></el-form-item><el-button type="primary" @click="investigate">只读调查</el-button></el-form><el-descriptions v-if="evidence" border :column="1"><el-descriptions-item v-for="(value,key) in evidence" :key="key" :label="String(key)"><pre>{{ value }}</pre></el-descriptions-item></el-descriptions></el-tab-pane>
			<el-tab-pane label="数据治理" name="lifecycle" v-if="can(B.lifecycleList)"><el-table :data="lifecycle" border><el-table-column v-for="column in columns(lifecycle)" :key="column" :prop="column" :label="column" show-overflow-tooltip/><el-table-column label="操作"><template #default="{row}"><el-button v-if="can(B.lifecycleUpdate)" type="warning" text @click="openResource('lifecycle', row)">调整策略</el-button></template></el-table-column></el-table></el-tab-pane>
			<el-tab-pane label="敏感导出" name="exports" v-if="canAnyExport"><el-form inline><el-form-item label="导出 ID"><el-input v-model="exportForm.exportId" placeholder="工单约定的唯一 ID"/></el-form-item><el-form-item label="定义"><el-input v-model="exportForm.definitionCode"/></el-form-item><el-form-item label="范围"><el-input v-model="exportForm.scope"/></el-form-item><el-form-item label="行数"><el-input-number v-model="exportForm.rowLimit" :min="1" :max="5000"/></el-form-item><el-form-item label="原因"><el-input v-model="exportForm.reason" maxlength="200"/></el-form-item></el-form><div class="toolbar"><el-button v-if="can(B.exportRequest)" type="primary" :loading="submitting" @click="runExport('request')">申请</el-button><el-button v-if="can(B.exportApprove)" type="warning" :loading="submitting" @click="openExportApproval">异人批准</el-button><el-button v-if="can(B.exportGenerate)" type="danger" :loading="submitting" @click="openExportGenerate">生成</el-button><el-button v-if="can(B.exportDownload)" :loading="submitting" @click="downloadExport">下载</el-button></div><el-descriptions v-if="exportResult" data-state="success" border :column="1"><el-descriptions-item v-for="(value,key) in exportResult" :key="key" :label="String(key)">{{ value }}</el-descriptions-item></el-descriptions><el-empty v-else data-state="empty" description="尚无导出结果"/></el-tab-pane>
		</el-tabs>

		<el-dialog v-model="releaseVisible" title="玩法发布工作流" width="720px" destroy-on-close><el-form label-width="110px"><el-form-item label="玩法 / 发布"><el-input :model-value="`${release.gameId} / ${release.releaseId}`" disabled/></el-form-item><el-form-item label="动作"><el-select v-model="release.action"><el-option v-for="action in allowedReleaseActions" :key="action" :label="releaseLabels[action]" :value="action"/></el-select></el-form-item><el-form-item label="版本" v-if="release.action==='draft'"><el-input v-model="release.version"/></el-form-item><el-form-item label="配置 JSON" v-if="release.action==='draft'"><el-input v-model="release.profile" type="textarea" :rows="5"/></el-form-item><el-form-item label="灰度比例" v-if="release.action==='canary'"><el-input-number v-model="release.percentage" :min="1" :max="100"/></el-form-item><el-form-item label="操作原因" required><el-input v-model="release.reason" maxlength="200"/></el-form-item><approval-fields v-if="isHighRiskRelease" v-model="approval"/></el-form><template #footer><el-button @click="releaseVisible=false">取消</el-button><el-button type="danger" :loading="submitting" @click="submitRelease">确认执行</el-button></template></el-dialog>
		<el-dialog v-model="resourceVisible" :title="resourceTitle" width="640px" destroy-on-close><el-form label-width="110px"><el-form-item label="目标 ID"><el-input v-model="resource.id" disabled/></el-form-item><el-form-item label="变更 JSON" required><el-input v-model="resource.payload" type="textarea" :rows="6"/></el-form-item><el-form-item label="操作原因" required><el-input v-model="resource.reason" maxlength="200"/></el-form-item><approval-fields v-model="approval"/></el-form><template #footer><el-button @click="resourceVisible=false">取消</el-button><el-button type="danger" :loading="submitting" @click="submitResource">异人审批后执行</el-button></template></el-dialog>
		<el-dialog v-model="exportApprovalVisible" :title="exportApprovalAction==='approve'?'批准敏感导出':'生成敏感导出'" width="620px" destroy-on-close><approval-fields v-model="approval"/><template #footer><el-button @click="exportApprovalVisible=false">取消</el-button><el-button type="danger" :loading="submitting" @click="confirmExportApproval">确认执行</el-button></template></el-dialog>
	</div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import ApprovalFields from '/@/components/admin/ApprovalFields.vue';
import { createRequestId, isVersionConflict, operationsApi, resourceEtag, type ApprovalHeaders, type ExportAction, type ReleaseAction } from '/@/api/operations';
import { ADMIN_BUTTONS as B, canUseAdminButton as can } from '/@/utils/adminPermission';

const active=ref('profiles'), loading=ref(false), submitting=ref(false), balanced=ref(true), evidence=ref<Record<string,unknown>|null>(null), loadError=ref('');
const profiles=ref<any[]>([]), switches=ref<any[]>([]), appeals=ref<any[]>([]), differences=ref<any[]>([]), lifecycle=ref<any[]>([]);
const businessDate=ref(new Date().toISOString().slice(0,10));
const rows=(value:any)=>value?.data?.items??value?.data?.rows??value?.items??value?.rows??[];
const columns=(data:any[])=>Object.keys(data[0]??{}).filter(key=>!/(token|secret|password|signature)/i.test(key)).slice(0,8);
const profileColumns=computed(()=>columns(profiles.value));
const approval=reactive<ApprovalHeaders>({approvalId:'',approverId:'',expires:'',signature:''});
const emptyApproval=()=>Object.assign(approval,{approvalId:'',approverId:'',expires:'',signature:''});
const validApproval=()=>Object.values(approval).every(value=>value.trim());

const releaseVisible=ref(false);
const release=reactive({gameId:'',releaseId:'',action:'validate' as ReleaseAction,version:'',profile:'{}',percentage:10,reason:''});
const releaseButton:Record<ReleaseAction,any>={draft:B.releaseDraft,validate:B.releaseValidate,submit:B.releaseSubmit,approve:B.releaseApprove,canary:B.releaseCanary,activate:B.releaseActivate,rollback:B.releaseRollback};
const releaseLabels:Record<ReleaseAction,string>={draft:'保存草稿',validate:'机器校验',submit:'提交审批',approve:'异人批准',canary:'灰度发布',activate:'全量生效',rollback:'回滚'};
const allowedReleaseActions=computed(()=>(Object.keys(releaseButton) as ReleaseAction[]).filter(action=>can(releaseButton[action])));
const isHighRiskRelease=computed(()=>['canary','activate','rollback'].includes(release.action));
const openRelease=async(row:any)=>{ Object.assign(release,{gameId:String(row.gameId??row.id??''),releaseId:String(row.releaseId??row.versionId??''),action:allowedReleaseActions.value[0]??'validate',version:'',profile:'{}',percentage:10,reason:''});emptyApproval();releaseVisible.value=true;loading.value=true;try{const result:any=await operationsApi.getGameRelease(release.gameId,release.releaseId);const value=result?.data??result;release.version=String(value?.version??'');release.profile=JSON.stringify(value?.profile??{},null,2)}catch{releaseVisible.value=false;loadError.value='发布详情加载失败，未进入操作状态。'}finally{loading.value=false} };

const resourceVisible=ref(false), resource=reactive({type:'' as 'switch'|'appeal'|'lifecycle'|'',id:'',etag:'',payload:'{}',reason:''});
const resourceTitle=computed(()=>resource.type ? {switch:'变更运营开关',appeal:'处理客服申诉',lifecycle:'调整数据生命周期'}[resource.type] : '');
const resourcePayload=(type:'switch'|'appeal'|'lifecycle',row:any)=>{
	if(type==='switch')return {allowCreate:!!row.allowCreate,allowExistingFinish:!!row.allowExistingFinish,minimumClientVersion:String(row.minimumClientVersion??''),routeVersion:String(row.routeVersion??'')};
	if(type==='appeal')return {resolution:'NEED_MORE_EVIDENCE',evidenceReference:''};
	return {hotDays:Number(row.hotDays??0),archiveDays:Number(row.archiveDays??0),deleteAfterDays:Number(row.deleteAfterDays??0),legalHold:!!row.legalHold,anonymizeOnDeletion:!!row.anonymizeOnDeletion};
};
const openResource=(type:'switch'|'appeal'|'lifecycle',row:any)=>{let etag:string;try{etag=resourceEtag(row._etag)}catch(error){return ElMessage.error(error instanceof Error?error.message:'资源缺少版本标识，请刷新后重试')}Object.assign(resource,{type,id:String(row.id??row.gameId??row.dataType??row.appealId??''),etag,payload:JSON.stringify(resourcePayload(type,row),null,2),reason:''});emptyApproval();resourceVisible.value=true;};

async function loadAll(){loading.value=true;loadError.value='';const calls:any[]=[];const targets:any[]=[];if(can(B.profileList)){calls.push(operationsApi.gameProfiles({limit:100}));targets.push(profiles)}if(can(B.switchList)){calls.push(operationsApi.operationSwitches());targets.push(switches)}if(can(B.appealList)){calls.push(operationsApi.appeals({limit:100,status:'OPEN'}));targets.push(appeals)}if(can(B.lifecycleList)){calls.push(operationsApi.lifecyclePolicies());targets.push(lifecycle)}const results=await Promise.allSettled(calls);results.forEach((result,index)=>{targets[index].value=result.status==='fulfilled'?rows(result.value):[]});loading.value=false;if(results.some(r=>r.status==='rejected'))loadError.value='部分授权数据加载失败；失败区域已清空，避免显示过期数据。';if(can(B.reconciliation))await loadReconciliation();}
async function loadReconciliation(){try{const result:any=await operationsApi.reconciliation(businessDate.value);differences.value=rows(result);balanced.value=result?.data?.balanced??differences.value.length===0}catch{differences.value=[];balanced.value=false;loadError.value='账务对账加载失败，请重试。'}}
async function investigate(){if(!investigation.roomId||!investigation.reason.trim())return ElMessage.warning('请填写房间 ID 和调查原因');try{const result:any=await operationsApi.gameInvestigation(investigation.roomId,{from:0,to:10000,set:investigation.set},investigation.reason);evidence.value=result?.data??result}catch{evidence.value=null;loadError.value='调查证据加载失败，请检查权限、房间 ID 与时间范围。'}}
const investigation=reactive({roomId:'',set:0,reason:''});
async function confirmed(label:string){try{await ElMessageBox.confirm(`将执行“${label}”。系统会记录目标、原因和请求号，且不会直接修改牌局或余额。`,'高风险确认',{type:'warning',confirmButtonText:'确认执行'});return true}catch{return false}}
async function submitRelease(){if(!release.reason.trim())return ElMessage.warning('必须填写操作原因');if(isHighRiskRelease.value&&!validApproval())return ElMessage.warning('请填写完整审批凭证');let profile:unknown={};try{profile=JSON.parse(release.profile)}catch{return ElMessage.error('配置 JSON 无效')}if(!await confirmed(releaseLabels[release.action]))return;submitting.value=true;try{const command:any={requestId:createRequestId(),reason:release.reason};if(release.action==='draft')Object.assign(command,{version:release.version,profile,previousVersion:''});if(release.action==='canary')command.percentage=release.percentage;await operationsApi.gameRelease(release.gameId,release.releaseId,release.action,command,isHighRiskRelease.value?approval:undefined);ElMessage.success('操作成功');releaseVisible.value=false;await loadAll()}finally{submitting.value=false}}
async function submitResource(){if(!resource.reason.trim()||!validApproval())return ElMessage.warning('请填写原因和完整审批凭证');let payload:any;try{payload=JSON.parse(resource.payload)}catch{return ElMessage.error('变更 JSON 无效')}if(!await confirmed(resourceTitle.value))return;submitting.value=true;try{const command={...payload,requestId:createRequestId(),reason:resource.reason};if(resource.type==='switch')await operationsApi.updateOperationSwitch(resource.id,command,approval,resource.etag);if(resource.type==='appeal')await operationsApi.resolveAppeal(resource.id,command,approval,resource.etag);if(resource.type==='lifecycle')await operationsApi.updateLifecyclePolicy(resource.id,command,approval,resource.etag);ElMessage.success('操作成功');resourceVisible.value=false;await loadAll()}catch(error){if(isVersionConflict(error)){resourceVisible.value=false;ElMessage.error('保存失败：资源已被其他操作员更新，已刷新为权威状态，请重新检查后再提交');await loadAll();return}throw error}finally{submitting.value=false}}
const exportForm=reactive({exportId:'',definitionCode:'club-member-support',scope:'CLUB',rowLimit:100,reason:''});
const exportResult=ref<Record<string,unknown>|null>(null),exportApprovalVisible=ref(false),exportApprovalAction=ref<'approve'|'generate'>('approve');
const canAnyExport=computed(()=>can(B.exportRequest)||can(B.exportApprove)||can(B.exportGenerate)||can(B.exportDownload));
const exportCommand=()=>({requestId:createRequestId(),reason:exportForm.reason,definitionCode:exportForm.definitionCode,scope:exportForm.scope,rowLimit:exportForm.rowLimit});
async function runExport(action:ExportAction,approved=false){if(!exportForm.exportId.trim()||!exportForm.reason.trim())return ElMessage.warning('请填写导出 ID 和原因');submitting.value=true;try{const result:any=await operationsApi.sensitiveExport(exportForm.exportId,action,exportCommand(),approved?approval:undefined);exportResult.value=result?.data??result;exportApprovalVisible.value=false;ElMessage.success('导出工作流操作成功')}finally{submitting.value=false}}
const openExportApproval=()=>{exportApprovalAction.value='approve';emptyApproval();exportApprovalVisible.value=true};
const openExportGenerate=()=>{exportApprovalAction.value='generate';emptyApproval();exportApprovalVisible.value=true};
async function confirmExportApproval(){if(!validApproval())return ElMessage.warning('请填写完整审批凭证');await runExport(exportApprovalAction.value,true)}
async function downloadExport(){if(!exportForm.exportId.trim())return ElMessage.warning('请填写导出 ID');submitting.value=true;try{const blob:any=await operationsApi.downloadSensitiveExport(exportForm.exportId);const url=URL.createObjectURL(blob instanceof Blob?blob:new Blob([blob]));const link=document.createElement('a');link.href=url;link.download=`admin-export-${exportForm.exportId}.json`;link.click();URL.revokeObjectURL(url)}finally{submitting.value=false}}
onMounted(loadAll);
</script>

<style scoped>
.operations-page{min-height:100%;padding:24px;background:#f3f0e8;color:#17362d}.hero{display:flex;justify-content:space-between;padding:26px;border:1px solid #b9c9bc;border-radius:16px;background:#fffdf7}.hero h1{font:700 34px "Songti SC",serif;margin:4px 0}.hero p{margin:0;color:#5d7067}.eyebrow{font:700 12px Georgia,serif!important;letter-spacing:.2em;color:#b35a2e!important}.workspace{margin-top:18px;padding:20px;border-radius:16px;background:#fffdf7}.toolbar{display:flex;align-items:center;gap:12px;margin-bottom:14px}.state-alert{margin-bottom:14px}pre{white-space:pre-wrap;word-break:break-all;margin:0}@media(max-width:800px){.operations-page{padding:10px}.hero{display:block}.hero h1{font-size:26px}}
</style>
